// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  webDesignSidebar: [{ type: 'autogenerated', dirName: 'web-design' }],
  aspNetSidebar: [{ type: 'autogenerated', dirName: 'asp-net' }],

  // But you can create a sidebar manually
  
  // tutorialSidebar: [
  //   'intro',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
  // webDesignSidebar: [
  //   'web-design/intro',
  //   {
  //     type: 'category',
  //     label: 'Уеб дизайн',
  //     items: [
  //       'web-design/colors',
  //       'web-design/typography',
  //       'web-design/layout',
  //     ],
  //   },
  // ]
};

export default sidebars;
